### ISSUE TITLE
如何在MacOS上连校园集群？

### ISSUE THREAD

**Issue by HuangJiaLian** [HuangJiaLian/SoftMatterDiscuss#2]
我想要有图形界面。我装了个putty不知道怎么用。

**Comment by HuangJiaLian** [comment]
@974918051 
Putty是ssh客户端，登录到集群是Linux终端，没有图形界面。Mac下没有必要使用Putty, 用自带的终端即可连接集群终端。

## 注意
如果使用校园网则直接用ip登录集群即可。校外网络，需要使用[EasyConnect](https://vpn.wzu.edu.cn/com/installClient_en.html#auto-common)工具连接到学校，然后连接集群即可。

## 远程登录的方法:
使用Mac下自带的Terminal工具。
例如:
```bash
ssh hj@192.168.12.7
```
替换ip地址为集群的ip即可连接。

## 文件传输的方法:
使用图形化的文件传输工具[FileZilla Client](https://filezilla-project.org/)即可。
连接方式: File->Site Manager -> New Site 配置如下:
Protocol: SFTP --SSH File Transfer Protocol
Host: ip地址 Port: 22
Logon: Normal
User:集群用户名
Password： 集群用户名密码

点击连接即可。

**Comment by HuangJiaLian** [comment]
@974918051  有问题请直接在issue页面回复。

**Comment by 974918051** [comment]
多谢杰德斯，问题已经解决了。

**Comment by HuangJiaLian** [comment]
好的。 @974918051

**Comment by HuangJiaLian** [comment]
## Finder中挂载远程网络硬盘

### 使用软件
1. 安装fuse
2. sshfs命令
参考: 
[1] https://wxnacy.com/2018/04/12/osx-user-sshfs/
[2] https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh

### 更新MacOS Bigsur后无法使用的解决方法
更新MAC系统后，发现无法正常使用挂载功能。可以尝试:
先卸载原有的osxfuse, 命令行中执行: 

```bash
brew uninstall osxfuse
```

之后重装和设置，如下:

> As described by @andreyboxti I did the following:
> `brew install --cask osxfuse`
> 
> And then added the permissions in the `Settings > Security & Privacy > General` to allow the extension
> 
> It works now!

参考: https://github.com/osxfuse/osxfuse/issues/705#issuecomment-742440871

在.bashr/.zshrc文件中添加一个类似的别名, 将远程的硬盘挂在到本地

```
alias Jmount_cluster='sshfs jack@10.1.12.198:/home/jack/ /Users/mac/Mounts/Jack_soft -ovolname=Jack_soft'
```

@yychenleslie
